/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
FIXED: Smooth + slow mouse/touch rotation with inertia
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import islandScene from '../assets/3d/island.glb'

const ROTATION_SENSITIVITY = 0.003   // ⬅ adjust if needed (smaller = slower)
const INERTIA_DAMPING = 0.92         // ⬅ smooth stop

const Island = ({
  isRotating,
  setIsRotating,
  setCurrentStage,
  ...props
}) => {
  const islandRef = useRef()
  const { gl } = useThree()
  const { nodes, materials } = useGLTF(islandScene)

  const lastX = useRef(0)
  const rotationSpeed = useRef(0)

  const getClientX = (e) =>
    e.touches ? e.touches[0].clientX : e.clientX

  /* ================= POINTER EVENTS ================= */

  const handlePointerDown = (e) => {
    e.stopPropagation()
    setIsRotating(true)
    lastX.current = getClientX(e)
  }

  const handlePointerMove = (e) => {
    if (!isRotating) return

    const currentX = getClientX(e)
    const deltaX = currentX - lastX.current
    lastX.current = currentX

    const rotationDelta = deltaX * ROTATION_SENSITIVITY

    islandRef.current.rotation.y += rotationDelta
    rotationSpeed.current = rotationDelta
  }

  const handlePointerUp = () => {
    setIsRotating(false)
  }

  /* ================= KEYBOARD SUPPORT ================= */

  const handleKeyDown = (e) => {
    if (e.key === 'ArrowLeft') {
      setIsRotating(true)
      rotationSpeed.current = 0.02
    }
    if (e.key === 'ArrowRight') {
      setIsRotating(true)
      rotationSpeed.current = -0.02
    }
  }

  const handleKeyUp = () => {
    setIsRotating(false)
  }

  /* ================= FRAME LOOP ================= */

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= INERTIA_DAMPING

      if (Math.abs(rotationSpeed.current) < 0.0001) {
        rotationSpeed.current = 0
      }

      islandRef.current.rotation.y += rotationSpeed.current
    }

    // ---- Stage detection ----
    const rotation =
      ((islandRef.current.rotation.y % (2 * Math.PI)) + 2 * Math.PI) %
      (2 * Math.PI)

    if (rotation > 5.45 && rotation < 5.85) setCurrentStage(4)
    else if (rotation > 0.85 && rotation < 1.3) setCurrentStage(3)
    else if (rotation > 2.4 && rotation < 2.6) setCurrentStage(2)
    else if (rotation > 4.25 && rotation < 4.75) setCurrentStage(1)
    else setCurrentStage(null)
  })

  /* ================= EVENT BINDINGS ================= */

  useEffect(() => {
    const canvas = gl.domElement

    canvas.addEventListener('pointerdown', handlePointerDown)
    canvas.addEventListener('pointermove', handlePointerMove)
    canvas.addEventListener('pointerup', handlePointerUp)
    canvas.addEventListener('pointerleave', handlePointerUp)

    document.addEventListener('keydown', handleKeyDown)
    document.addEventListener('keyup', handleKeyUp)

    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown)
      canvas.removeEventListener('pointermove', handlePointerMove)
      canvas.removeEventListener('pointerup', handlePointerUp)
      canvas.removeEventListener('pointerleave', handlePointerUp)

      document.removeEventListener('keydown', handleKeyDown)
      document.removeEventListener('keyup', handleKeyUp)
    }
  }, [gl, isRotating])

  /* ================= MODEL ================= */

  return (
    <a.group ref={islandRef} {...props}>
      <mesh geometry={nodes.polySurface944_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface945_tree1_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface946_tree2_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface947_tree1_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface948_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface949_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.pCube11_rocks1_0.geometry} material={materials.PaletteMaterial001} />
    </a.group>
  )
}

export default Island
useGLTF.preload(islandScene)
